### PR TITLE
Adds history & ssh modules

### PR DESCRIPTION
**Pull request by slmingol**
Adds 2 additional modules, history & ssh.

### CODE REVIEW

**Comment by chris-marsh** [comment]
Thanks for the input and modules. Pureline hasn't received much of much attention recently and I need to get a few things tidied up. The WIP branch has many changes that I haven't pulled into the master branch yet ... including an SSH module. Can you have a look at the WIP version and let me know what you think?

**Comment by chris-marsh** [comment]
The WIP branch has now been merged into master bringing changes to the modules and the SSH module I mentioned above. This obviously has cerated conflicts for you PR.

I'd like if you could look at the new SSH module and see what you think. It would be great if you could redo the PR for the history module too.

**Comment by slmingol** [comment]
Sure I'll take a look and see how to rebase my changes against your latest updates.

**Comment by chris-marsh** [comment]
An ssh module is now included.

**Pull request closed without merging**
