### PR TITLE
Various Git improvement

### PR DESCRIPTION
**Pull request by dzamlo**

### CODE REVIEW

**Comment by chris-marsh** [comment]
I like the git functions.  I think the display/symbols need something more as its not immediately obvious what the prompt is showing.
screen10

**Comment by dzamlo** [comment]
I agree that the symbols for the ahead/behind need to be improved. I tried using Unicode arrow ( like ↑ ) but this was really not legible. Maybe the simple 'A' and 'B' may be a better idea ?

**Comment by chris-marsh** [comment]
[zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt) use those arrows, but they aren't very distinct with my fonts either. These unicode triangles seem well supported;

▲ - U+25B2 BLACK UP-POINTING TRIANGLE
▼ - U+25BC BLACK DOWN-POINTING TRIANGLE

I prefer these, but I'm not sure how common they are;

⮝ - U+2B9D
⮟ - U+2B9F

**Comment by dzamlo** [comment]
⮝ - U+2B9D and ⮟ - U+2B9F seems to not be very common, for example they doesn't work on my Android phone. On the other hand, that also true of some other symbols used by pureline.

**Pull request merged**
