### PR TITLE
Added options PL_PROMPT_ROOT_BG, PL_PROMPT_ROOT_FG for prompt_module

### PR DESCRIPTION
**Pull request by acidnik**

### CODE REVIEW

**Comment by chris-marsh** [comment]
Thanks for the PR. I'll review it soon.

**Comment by chris-marsh** [comment]
I'm not sure I want to hard code colors. Pureline is currently only installed locally per user. Therefore each user will have (or can have) their own config file. The same is true of root. Root can have its own config file with whatever colors are wanted.

**Comment by CRCinAU** [comment]
Correct me if I'm wrong, but if we do a global installation such as in my issue, a user could still have their own colours, but by default, having the red / green is an instant reminder.

This seems to bring it inline with other prompt tools I've seen.

**Comment by chris-marsh** [comment]
Fair enough. I played about with the PR  and sane defaults are good idea.

**Pull request merged**
