### PR TITLE
Add Conda environment module

### PR DESCRIPTION
**Pull request by darkvertex**
This adds a very very simple module (based off the code for the `virtual_env_module`) to highlight the name of the **[Conda](https://docs.conda.io/en/latest/)** environment you are in.

For the unaware: Conda environments are very similar to virtualenvs but they are a different beast as they can also handle non-Python software, or even the version of Python itself. They are very powerful.

### CODE REVIEW

**Comment by PaulHiemstra** [comment]
This would be a very cool addition as I use conda environments instead of virtualenv.

**Comment by andrzejnovak** [comment]
👍 I was literally just about to make this PR.

**Comment by chris-marsh** [comment]
Thanks for the input and apologies for the long delay in replying.

I'm reworking the way custom modules/segments canbe added.

My original idea for pureline was to keep it a simple single file system. This premise however, excludes adding a lot of extra code, meaning functionality which would be useful to some is excluded.

The new system will allow unlimited plugin files to be 'sourced' into pureline, while keeping the core simple and small. I will try to work your code in soon.

**Comment by PaulHiemstra** [comment]
No problem Chris, this probably is all volunteer work that you have to fit around your other work.

**Comment by darkvertex** [comment]
Thanks for incorporating the changes @chris-marsh 🎉

**Comment by chris-marsh** [comment]
Its good to have more choice for people to use :)
I was thinking ... what about the conda and virtual env code being merged to be a python_section?

Something like;
if conda_env set
... do this
else if virtual_env set
...do that?

**Comment by darkvertex** [comment]
You can but I'd like to point out that conda and virtualenv are not mutually exclusive.

You _probably_ wouldn't use virtualenv inside a conda env, but you _can_, so 👍 for combining the code, but don't do "if conda, else if virtualenv", because you can mix both and then pureline will be omitting one in that scenario. It should detect both, not one or the other.

**Pull request merged**
